doc/installing.rst

That is, the PyPI & conda-forge packages for 0.0.9.
(Also a little grammatical thing near the end.)

corrected statement about packages and linked

---

doc/whats_new.rst
xsimlab/drivers.py
xsimlab/tests/test_drivers.py

Convert scalar values to scalars (not 0-d arrays) from input Dataset

---

doc/scripts/advection_model.py
xsimlab/dot.py
xsimlab/drivers.py
xsimlab/model.py
xsimlab/process.py
xsimlab/stores.py
xsimlab/tests/fixture_model.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_formatting.py
xsimlab/tests/test_model.py
xsimlab/tests/test_process.py
xsimlab/tests/test_utils.py
xsimlab/tests/test_xr_accessor.py
xsimlab/utils.py
xsimlab/xr_accessor.py

New style classes everywhere

---

doc/api.rst
doc/whats_new.rst
xsimlab/process.py
xsimlab/tests/fixture_model.py
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

Leverage variables default values in the xarray interface

---

doc/create_model.rst
doc/run_model.rst
doc/scripts/advection_model.py
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/tests/fixture_model.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_drivers.py
xsimlab/variable.py

Static variables

---

doc/framework.rst
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/model.py
xsimlab/tests/fixture_model.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_xr_accessor.py
xsimlab/variable.py
xsimlab/xr_accessor.py

Validate values given as input or set in foreign processes  

---

doc/whats_new.rst
xsimlab/drivers.py
xsimlab/tests/fixture_model.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

Check (transpose) the dimensions of input variables 

---

doc/whats_new.rst
xsimlab/drivers.py
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

validate='nothing' to validate=None

---

doc/api.rst
doc/whats_new.rst
xsimlab/tests/test_validators.py
xsimlab/validators.py

- ~~Add links to API reference in the user guide.~~ Let's add (in another PR) a whole subsection for variable default values, validators and converters in the user guide (create models).

Add validators

---

doc/whats_new.rst
xsimlab/drivers.py
xsimlab/process.py
xsimlab/tests/fixture_model.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_process.py
xsimlab/variable.py

Add / execute variable converters

---

doc/api.rst
doc/whats_new.rst
xsimlab/__init__.py
xsimlab/drivers.py
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/fixture_model.py
xsimlab/tests/test_model.py
xsimlab/tests/test_variable.py
xsimlab/variable.py

Index variables

---

doc/whats_new.rst
xsimlab/tests/fixture_model.py
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

Reset output variables: avoid update attrs in original dataset

---

doc/api.rst
doc/whats_new.rst
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

Clean-up and add some properties/methods to Dataset.xsimlab

---

ci/requirements/doc.yml
readthedocs.yml

Follow-up on #105 that didn't work.
This is really frustrating...
Also update RTD config file to v2.

Workaround rtd 2

---

doc/api.rst
doc/create_model.rst
doc/develop.rst
doc/faq.rst
doc/framework.rst
doc/index.rst
doc/inspect_model.rst
doc/io_storage.rst
doc/monitor.rst
doc/release_procedure.rst
doc/run_model.rst
doc/scripts/advection_model.py
doc/testing.rst
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/model.py
xsimlab/process.py
xsimlab/stores.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_model.py
xsimlab/tests/test_stores.py
xsimlab/tests/test_utils.py
xsimlab/tests/test_xr_accessor.py
xsimlab/utils.py
xsimlab/xr_accessor.py

Run batches of simulations

---

xsimlab/stores.py
xsimlab/tests/test_stores.py
xsimlab/tests/test_utils.py
xsimlab/utils.py

ZarrSimulationStore updates

---

doc/api.rst
doc/framework.rst
doc/whats_new.rst
xsimlab/__init__.py
xsimlab/formatting.py
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_model.py
xsimlab/tests/test_process.py
xsimlab/tests/test_xr_accessor.py
xsimlab/variable.py
xsimlab/xr_accessor.py

Add "object" variables

---

.github/workflows/test.yml
doc/conf.py
doc/faq.rst
doc/framework.rst
doc/index.rst
doc/installing.rst
doc/io_storage.rst
doc/run_model.rst
doc/run_parallel.rst
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/model.py
xsimlab/process.py
xsimlab/stores.py
xsimlab/tests/__init__.py
xsimlab/tests/test_model.py
xsimlab/tests/test_stores.py
xsimlab/tests/test_xr_accessor.py
xsimlab/utils.py
xsimlab/xr_accessor.py

Run model(s) in parallel using dask

---

doc/whats_new.rst
xsimlab/drivers.py
xsimlab/stores.py
xsimlab/tests/__init__.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_stores.py
xsimlab/tests/test_xr_accessor.py

...so that batches of simulations may run in parallel using ``dask.distributed`` (fix serialization issues).

Refactor Xarray simulation driver

---

.gitignore
doc/api.rst
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/model.py
xsimlab/stores.py
xsimlab/tests/test_model.py

Add Model.cache property

---

doc/whats_new.rst
xsimlab/process.py
xsimlab/tests/test_process.py

Apply process decorator on a attrs-decorated class

---

doc/whats_new.rst
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

Fix update clocks

---

.github/workflows/test.yml
ci/requirements/py37.yml
ci/requirements/py38.yml
ci/requirements/py39.yml
doc/develop.rst
doc/run_model.rst
doc/whats_new.rst
xsimlab/formatting.py
xsimlab/ipython.py
xsimlab/model.py
xsimlab/tests/test_ipython.py

Add IPython %create_setup magic command

---

doc/framework.rst
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/tests/test_drivers.py

Ensure finalize simulation stage is always run

---

doc/api.rst
doc/framework.rst
doc/whats_new.rst
xsimlab/__init__.py
xsimlab/formatting.py
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_model.py
xsimlab/tests/test_process.py
xsimlab/tests/test_variable.py
xsimlab/tests/test_xr_accessor.py
xsimlab/variable.py
xsimlab/xr_accessor.py

Add group_dict variable

---

.github/workflows/test.yml
codecov.yml
doc/api.rst
doc/framework.rst
doc/whats_new.rst
xsimlab/__init__.py
xsimlab/dot.py
xsimlab/formatting.py
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_formatting.py
xsimlab/tests/test_model.py
xsimlab/tests/test_process.py
xsimlab/tests/test_stores.py
xsimlab/tests/test_variable.py
xsimlab/variable.py

Global variables (model-wise implicit linking)

---

CONTRIBUTING.rst
LICENSE
README.rst
doc/conf.py
doc/develop.rst
doc/faq.rst
doc/index.rst
doc/installing.rst
setup.py

Transfer repository to xarray-contrib
