xarray-contrib/xarray-simlab

.gitignore
doc/api.rst
doc/conf.py
xsimlab/model.py
xsimlab/tests/conftest.py
xsimlab/tests/test_xr_accessor.py
xsimlab/utils.py
xsimlab/xr_accessor.py
xsimlab/xr_interface.py

API refactoring and improvements for `Dataset.xsimlab` accessor.
The basic idea is to avoid as much as possible methods that modify the Dataset in place and instead provide a small set of consistent methods that we can easily chain together. The integration of `xsimlab.Model` objects should also be improved (e.g., using a context manager).
Related to #2 and #4 
TODO:
snapshot attributes) that are related to `model` 
methods shouldn't be part of the public API anymore
(*) master clock can also be used for snapshots. master clock would then have both  `_xsimlab_clock` and `_xsimlab_master_clock` attributes. Implementation of `Dataset.xsimlab.clock_coords` is more straightforward too.

Dataset accessor API refactoring

---

xsimlab/tests/conftest.py
xsimlab/tests/test_variable.py
xsimlab/variable/base.py

length >1 tuples were not interpreted correctly.

Fix misinterpreted tuples passed as `allowed_dims` for `Variable`

---

doc/whats_new.rst
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

Better error messages when model object is missing or not a model object

---

doc/about.rst
doc/conf.py

Small doc updates

---

doc/run_model.rst
doc/whats_new.rst
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

Closes #35.
- High-level API for generating clock coordinate data (i.e., `start`, `end`, `step` arguments) is not supported anymore. This could be added back in a future release in a different, cleaner form. The new API is more consistent with how we set coordinates in xarray.
- `auto_adjust` clock coordinate labels has been removed (an error is
raised instead). A cleaner implementation should be added back in a future release (e.g., with options like `'nearest'` but also `'intersection'` to simply exclude invalid labels).
- It is now possible to use `Dataset.xsimlab.update_clocks` to update only some clock
coordinates (previously all clock coordinates were dropped first).

Simplify clocks API

---

xsimlab/tests/test_dot.py

Fix failing tests on travis (linux).
This is taken from dask.

Allow jpeg format to xfail in test_dot

---

xsimlab/variable.py

A workaround before (hopefully) a cleaner solution (see https://github.com/python-attrs/attrs/issues/340).
Re-use argument list from `attr.attrib` for `_CountingAttr.__init__()`. It should at least reduce the risk of breaking the code when new arguments are introduced.

Fix _CountingAttr hack with attrs master

---

xsimlab/drivers.py

This has been removed in xarray 0.13 and it wasn't used here.

Fix inplace arg removed in xarray

---

doc/whats_new.rst
xsimlab/model.py
xsimlab/tests/test_model.py

This was not explicitly checked. Now there will be a more meaningful error message. Also added tests.

Ensure no variable intent conflict when building a model

---

doc/create_model.rst
doc/environment.yml
doc/scripts/advection_model.py
doc/whats_new.rst
xsimlab/model.py
xsimlab/tests/test_model.py

- Closes #24
A possible way to customize processes is to use class inheritance. However, a current limitation is that foreign variables hard-code external classes, making it difficult to customize a model by replacing a process class by one of its sub-classes.
This PR address this issue by also including parent classes in the process name/class reverse lookup that is used to link foreign variables to their corresponding process when building a new model. Using the example in the docs, it is now possible to do something like:
```python
@xs.process
class AlternativeGrid1D(UniformGrid1D):
"""Give number of nodes instead of total length as input."""
spacing = xs.variable(description='uniform spacing')
nnodes = xs.variable(description='number of nodes')
length = xs.variable(intent='out')
x = …
```

Include parent classes in process name/class reverse lookup

---

doc/api.rst
doc/create_model.rst
doc/scripts/advection_model.py
doc/whats_new.rst
xsimlab/__init__.py
xsimlab/drivers.py
xsimlab/formatting.py
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/fixture_model.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_model.py
xsimlab/tests/test_process.py
xsimlab/utils.py

Closes #40.
Also provides more flexibility for #52.
This refactoring is also a step towards making the framework less invasive. Ideally, a process class could be also instantiated and used independently of any model. This is important for testing purposes! Currently it is supported for "runtime" methods but we need a solution for ``__init__`` too.
TODO:

Refactor process execution during a simulation

---

doc/index.rst
doc/testing.rst
doc/whats_new.rst
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_formatting.py
xsimlab/tests/test_model.py
xsimlab/tests/test_process.py
xsimlab/tests/test_utils.py
xsimlab/variable.py

This is a follow-up on #59 towards a less invasive framework.
``@process`` is now a thin wrapper around ``attr.s``. Applied on a class ``A``, it returns the class (almost) just as it was decorated with ``attr.s``. The more invasive modifications (custom properties, etc.) are now in a subclass of ``A`` that is created programmatically and accessible from ``A.__xsimlab_cls__`` (Model objects use the latter subclass instead of ``A`` directly).
The great advantage is that it is now possible to use instances of process-decorated classes independently of any Model, which is IMO a better solution than the approach proposed in #50 for testing the logic implemented in those classes.
Variables declared with ``intent='in'`` or ``intent='inout'`` are now included in``__init__`` generated by attr.
An …

Decouple process class from Model

---

doc/framework.rst
doc/scripts/advection_model.py
doc/whats_new.rst
xsimlab/formatting.py
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/fixture_model.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_model.py
xsimlab/tests/test_variable.py
xsimlab/variable.py

Closes #64 
The ``group`` parameter of ``xsimlab.variable()`` and ``xsimlab.on_demand()`` is depreciated in favor of the newly introduced ``groups`` parameter.

Allows setting multiple groups for a variable

---

doc/citation.rst
doc/conf.py
doc/environment.yml
doc/examples.rst

Removed notebook example, and instead added a link to `fastscape`.
It's better to have self-contained examples in the docs, and just add links for examples that depend on 3rd-party tools.

Update doc examples and citation sections

---

README.rst
doc/about.rst
doc/run_model.rst
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_xr_accessor.py
xsimlab/variable.py
xsimlab/xr_accessor.py

Refactor ``output_vars`` in the xarray extension

---

doc/conf.py
doc/whats_new.rst
setup.py
versioneer.py
xsimlab/_version.py
xsimlab/dot.py
xsimlab/drivers.py
xsimlab/formatting.py
xsimlab/model.py
xsimlab/process.py
xsimlab/utils.py
xsimlab/variable.py
xsimlab/xr_accessor.py

A few cases where `str.format()` is used instead of its corresponding f-string were left in the code due to readability. The rest should be taken care of.

Converted old string formatting to fstrings

---

doc/whats_new.rst
xsimlab/tests/fixture_process.py
xsimlab/tests/test_variable.py
xsimlab/variable.py

[PR#88](https://github.com/benbovy/xarray-simlab/pull/88) was closed and the code has been changed in order to work independently from the autodoc-feature ([PR#67](https://github.com/benbovy/xarray-simlab/pull/67)).
I use `variables_dict()` from `utils.py`.
Since attrs is already imported in `variables.py`, the following line would return the same result:
```python
description = attr.fields_dict(other_process_cls)[var_name].metadata["description"])
```
From my understanding, foreign variables always belong to xsimlab variables. Therefore, we technically could use `attr.fields_dict()` instead. What do you think, @benbovy ?
My first inclination was, to iterate over `variables_dict(other_process_cls).items()` but luckily, the construct makes it accessibly as is 👍 
There's already a test …

Propagate original description to foreign variables

---

ci/requirements/doc.yml
ci/requirements/py36.yml
ci/requirements/py37-attrs-dev.yml
ci/requirements/py37-xarray-dev.yml
ci/requirements/py37.yml
ci/requirements/py38.yml
doc/conf.py
doc/index.rst
doc/installing.rst
doc/io_storage.rst
doc/whats_new.rst
setup.py
xsimlab/drivers.py
xsimlab/model.py
xsimlab/stores.py
xsimlab/tests/fixture_model.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_stores.py
xsimlab/xr_accessor.py

This basically allows efficient storage of model outputs (compression, chunked data) in memory or on disk or on a distributed file system or could storage systems... and get back these simulation data as a lazily loaded xarray.Dataset (optionally dask arrays). The xarray/dask/zarr combo is amazing! :-)

Add zarr simulation output store

---

doc/whats_new.rst
xsimlab/tests/fixture_process.py
xsimlab/tests/test_variable.py
xsimlab/variable.py

Foreign variables: get metadata from reference variable

---

doc/api.rst
doc/monitor.rst
doc/scripts/progress_bar_hack.py
doc/whats_new.rst
xsimlab/__init__.py
xsimlab/monitoring.py
xsimlab/progress.py
xsimlab/tests/test_monitoring.py

Follow-up on #104
@rlange2 FYI I've done some updates in order to:
- Fix the html rendered docs (there were some small issues)
- Move `progress.py` to `monitoring.py`, as I expect that more built-in monitoring tools will be added in the future. I also removed exposing `ProgressBar` to the main namespace to avoid putting too much things in it (this approach is used in other libraries such as `dask.diagnostics` and `skopt.callbacks`).
- Add tests for the runtime_hook decorated functions

Progress bar follow-up

---

doc/io_storage.rst
doc/whats_new.rst
xsimlab/stores.py
xsimlab/tests/test_stores.py

Auto-resize zarr datasets in output store

---

doc/framework.rst
doc/io_storage.rst
xsimlab/dot.py
xsimlab/drivers.py
xsimlab/formatting.py
xsimlab/model.py
xsimlab/process.py
xsimlab/stores.py
xsimlab/tests/conftest.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_formatting.py
xsimlab/tests/test_model.py
xsimlab/tests/test_process.py
xsimlab/tests/test_stores.py
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

`store` (now `state`) is just a dictionary that maps a model variable to its current value.
`output_store` (now `store`) stores both input and output simulation data.

Rename store -> state and output_store -> store

---

doc/io_storage.rst
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/stores.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_formatting.py
xsimlab/tests/test_stores.py
xsimlab/tests/test_utils.py
xsimlab/utils.py
xsimlab/variable.py
xsimlab/xr_accessor.py

This adds the possibility to define some `zarr.creation.create` arguments both at model variable declaration and when calling `Dataset.xsimlab.run()`. Options supplied in the latter override options defined in variables.

Add encoding options for storing model variables 

---

xsimlab/drivers.py
xsimlab/tests/test_xr_accessor.py

Fix writing index variables for parallel batches

---

doc/whats_new.rst
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

Accept array-like input vars with no dimension labels

---

doc/whats_new.rst
xsimlab/formatting.py
xsimlab/tests/test_formatting.py

Fix line returns and attribute type

Autodoc fixes and tweaks

---

ci/requirements/doc.yml
doc/run_parallel.rst
doc/whats_new.rst
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/__init__.py
xsimlab/tests/test_process.py
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

This allows using Dask's processes and distributed schedulers for single-model parallelism, although those may not yield good performance when a lot of data is shared between the processes (model state). Support of those schedulers is still limited, i.e.,
- doesn't work well with ``hooks``
- doesn't work at all for attributes in process classes that are used in runtime methods but that are not declared as variables (i.e., not part of a model's state)
- doesn't work when ``validate='all'`` (validate foreign variables). 
The new design (only used for parallel runs): 
A process executor returns a dictionary that consists of a subset of its state dictionary with only its output variables (intent 'in' or 'inout'). The executor also accepts a state dictionary as an optional input argument, …

"Stateless" process executors

---

doc/whats_new.rst
xsimlab/tests/test_validators.py

Fix tests with ``attr`` v20.1.0.

Avoid using attr non-public API

---

doc/whats_new.rst
xsimlab/formatting.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_formatting.py
xsimlab/variable.py

Improve auto-generated docstrings of process variables

---

doc/whats_new.rst
xsimlab/stores.py
xsimlab/tests/test_stores.py

…able dtype is object or np.object. It works at runtime and the variable is successfully saved in the Dataset, but it fails at sabing to file Closes #144

Fix saving output variables with dtype=object

---

README.rst
doc/about.rst
doc/io_storage.rst
doc/whats_new.rst
xsimlab/drivers.py
xsimlab/stores.py
xsimlab/tests/fixture_model.py
xsimlab/tests/test_drivers.py
xsimlab/tests/test_xr_accessor.py
xsimlab/xr_accessor.py

This leaves `mask_and_scale` to its default value (`True`) when using `xarray.open_zarr()` to load back the dataset at the end of the simulation. For convenience, a new `decoding` parameter has been added to `xarray.Dataset.xsimlab.run()` to pass keyword arguments to `xarray.open_zarr()`.

Mask fill values in output dataset

---

doc/whats_new.rst
xsimlab/process.py
xsimlab/tests/test_process.py

Ensure process subclasses are process-decorated

---

doc/whats_new.rst
xsimlab/model.py
xsimlab/process.py
xsimlab/tests/fixture_process.py
xsimlab/tests/test_model.py
xsimlab/variable.py

Add optional cache for on-demand variables

---

doc/api.rst
doc/framework.rst
doc/monitor.rst
doc/run_model.rst
doc/whats_new.rst
xsimlab/__init__.py
xsimlab/drivers.py
xsimlab/hook.py
xsimlab/model.py
xsimlab/monitoring.py
xsimlab/process.py
xsimlab/tests/test_process.py
xsimlab/tests/test_signals.py

Runtime signals
